import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module.js';
import { DataSource, Like } from 'typeorm';
import { User } from './user/user.entity.js';
import { Post } from './post/post.entity.js';
import { Comment } from './comments/comments.entity.js';
import bcrypt from 'bcrypt';

async function run() {
  // Use NestJS application context to leverage AppModule TypeORM configuration
  const app = await NestFactory.createApplicationContext(AppModule);
  const dataSource = app.get(DataSource);
  
  const userRepository = dataSource.getRepository(User);
  const postRepository = dataSource.getRepository(Post);
  const commentRepository = dataSource.getRepository(Comment);

  console.log('--- Database Seeding Started ---');

  // Find users generated by seed (matching username like 'user_%')
  console.log('Identifying existing seeded users...');
  const seededUsers = await userRepository.find({
    where: { username: Like('user_%') }
  });
  const seededUserUuids = seededUsers.map(u => u.uuid);

  if (seededUserUuids.length > 0) {
    console.log(`Cleaning ${seededUserUuids.length} existing seeded users and their posts/comments...`);
    
    // 1. Delete comments written by seeded users
    await commentRepository.createQueryBuilder('comment')
      .delete()
      .where('ownerUuid IN (:...uuids)', { uuids: seededUserUuids })
      .execute();

    // 2. Delete comments written on posts owned by seeded users
    await commentRepository.createQueryBuilder('comment')
      .delete()
      .where('postUuid IN (SELECT uuid FROM posts WHERE ownerUuid IN (:...uuids))', { uuids: seededUserUuids })
      .execute();

    // 3. Delete posts owned by seeded users
    await postRepository.createQueryBuilder('post')
      .delete()
      .where('ownerUuid IN (:...uuids)', { uuids: seededUserUuids })
      .execute();

    // 4. Delete the seeded users themselves
    await userRepository.createQueryBuilder('user')
      .delete()
      .where('uuid IN (:...uuids)', { uuids: seededUserUuids })
      .execute();
  } else {
    console.log('No existing seeded data found to clean.');
  }

  // Generate 10 users
  console.log('Generating 10 users...');
  const users: User[] = [];
  const hashedPassword = await bcrypt.hash('password123', 10);
  
  for (let i = 1; i <= 10; i++) {
    const user = userRepository.create({
      username: `user_${i}`,
      email: `user${i}@example.com`,
      password: hashedPassword,
      image: `https://api.dicebear.com/7.x/avataaars/svg?seed=user_${i}`
    });
    users.push(await userRepository.save(user));
  }
  console.log(`Created ${users.length} users.`);

  // Generate 50 posts distributed among those users
  console.log('Generating 50 posts...');
  const posts: Post[] = [];
  for (let i = 1; i <= 50; i++) {
    // Distribute posts evenly among the 10 users
    const owner = users[(i - 1) % users.length];
    const post = postRepository.create({
      title: `Interesting Tech Post ${i}`,
      describe: `This is the detailed content for post number ${i}. It describes some cool tech concepts and features.`,
      image: `https://picsum.photos/seed/post_${i}/800/600`,
      owner: owner,
      likes: Math.floor(Math.random() * 50),
      date: new Date(Date.now() - i * 3600000) // Spread posts chronologically
    });
    posts.push(await postRepository.save(post));
  }
  console.log(`Created ${posts.length} posts.`);

  // Generate comments on the seeded posts
  console.log('Generating comments...');
  const commentTexts = [
    'Great post! Thanks for sharing.',
    'Very interesting article, I learned a lot.',
    'Awesome explanation! Keep up the good work.',
    'I have a question about this, but overall nice post.',
    'Fully agree with the points mentioned here.',
    'This is exactly what I was looking for today.',
    'Simple, clear, and straight to the point. Loved it!'
  ];

  const comments: Comment[] = [];
  for (const post of posts) {
    // Add between 1 and 4 comments per post
    const commentsCount = Math.floor(Math.random() * 4) + 1;
    for (let c = 0; c < commentsCount; c++) {
      const commentOwner = users[Math.floor(Math.random() * users.length)];
      const commentText = commentTexts[Math.floor(Math.random() * commentTexts.length)];
      
      const comment = commentRepository.create({
        content: commentText,
        owner: commentOwner,
        post: post,
        date: new Date(post.date.getTime() + Math.random() * 3600000) // Commented shortly after the post was created
      });
      comments.push(comment);
    }
  }
  await commentRepository.save(comments);
  console.log(`Created ${comments.length} comments.`);

  await app.close();
  console.log('--- Database Seeding Completed Successfully ---');
}

run().catch(err => {
  console.error('Error seeding database:', err);
  process.exit(1);
});
